version: 2.1
orbs:
  codecov: codecov/codecov@1
executors:
  node:
    docker:
      - image: circleci/node:14.3
commands:
  checkout_and_install:
    description: 'Checks out source code, restores cache and installs npm dependencies'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm ci
jobs:
  build:
    executor: node
    steps:
      - checkout_and_install
      - save_cache:
          paths:
            - ~/.npm
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run: npm run build:ci
      - run: npm run test:ci
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - codecov/upload
      - run: npm run docs
      - store_artifacts:
          path: documentation
      - persist_to_workspace:
          root: dist
          paths:
            - .
  publish:
    executor: node
    steps:
      - checkout_and_install
      - attach_workspace:
          at: dist
      - run: npm run semantic-release

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
      - publish:
          context: hypertrace-publishing
          requires:
            - build
          filters:
            branches:
              only:
                - master
