name: publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: 'write'
      id-token: 'write'
      issues: 'write'
      pull-requests: 'write'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: NPM Install
        run: npm ci

      - name: Build
        run: npm run build:ci

      - uses: google-github-actions/auth@v2
        id: auth
        with:
          token_format: access_token
          workload_identity_provider: projects/1030413944741/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-publisher@hypertrace-repos.iam.gserviceaccount.com
      # Can't seem to get it to override this for publish otherwise...
      - name: Remove npmrc
        shell: bash
        run: rm .npmrc
      - name: Publish
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ steps.auth.outputs.access_token }}
          NPM_CONFIG_REGISTRY: ${{ secrets.GAR_NPM_PUBLISH_REGISTRY }}
